### ISSUE TITLE
how to implement page count for iOS epub reader?  [suggestions please]

### ISSUE THREAD

**Issue by devapalanisamy** [ricobeck/KFEpubKit#6]
Hi,

I am developing an epub reader for iOS using KFEpubKit . I can pass all "xhtml" files to uiwebview and get count for each chapter. but loading UIWebView for many times consume much time and memory. is there a better way to get page counts faster?

ibooks and SkyEpub count number of pages very fast. What do they do ? How do they do it? suggestions please.

**Comment by NamanMahi** [comment]
what are the codes needed for [self attributedStringAtURL:contentURL] this function ?
